services:
  - type: web
    name: paddleocr-backend
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "10000"
      - key: DISABLE_MODEL_SOURCE_CHECK
        value: "1"
    healthCheckPath: /docs
